version: '3.4'
services:
  app:
    image: acme.io/simple-service-user
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/userdb
      SPRING_DATASOURCE_USERNAME: sampleuser
      SPRING_DATASOURCE_PASSWORD: samplepass
    restart: on-failure
    ports:
      - 8700:8700
      - 9000:9000
  simple-consumer-user:
    image: acme.io/simple-consumer-user
    environment:
      SPRING_PROFILES_ACTIVE: default
    restart: on-failure
    ports:
      - 8701
    