# ===============================
# = Spring Profiles
# ===============================
spring:
  profiles:
    active: default
    locale: en
  application:
    name: simple-consumer-user

# ===============================
# = Server Ports.
# ===============================
server:
  port: 8701

# ===============================
# = Actuator.
# ===============================
management:
  health:
    defaults:
      enabled: false
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: ALWAYS  
  server:
    port: 9001